In [1]:
import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import praw
import prawcore
import random
import seaborn as sns

from config import Config, CONFIG_FILE_NAME
from util import *
import validate

sns.set_theme()

In [2]:
# To ensure everything's nice and deterministic
random.seed(0)
np.random.seed(0)

In [3]:
import logging

# This will log everything
LOG = True
if LOG:
    handler = logging.StreamHandler()
    handler.setLevel(logging.WARN)
    for logger_name in ("praw", "prawcore"):
        logger = logging.getLogger(logger_name)
        logger.setLevel(logging.DEBUG)
        logger.addHandler(handler)

In [5]:
# Create the Reddit instance to do all the API stuff with
reddit = init_reddit()

Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.

In [4]:
keywords = [
    r"trauma",
    r"trigger",
    r"toxic",
    r"manipulat",
    r"microaggression",
    r"autis",
    r"adhd",
    r"ocd",
    r"ptsd",
    r"bipolar",
    r"anxiety",
    r"depress",
    r"psycho",
    r"delusion",
    r"addict",
    r"abus",
    r"unstable",
    r"narcissis",
    r"addict",
    r"neurodivergen",
]

In [5]:
# config = Config.load()
config = Config.load(os.path.join("out", "run_0", CONFIG_FILE_NAME))

# Earliest post I can find: https://www.reddit.com/api/info.json?id=t1_c015001
first_id = config.time_ranges[0].start_id
last_id = config.time_ranges[-1].end_id

## Load comments

In [6]:
df, misses = load_data()
df

,id,time,sr_name,author_id,parent_id,post_id,upvotes,downvotes,body
0,26151671549,2009-12-31 19:01:19,IAmA,NaN,63325828058,17741786,2,0,How often do you deal with patient's nightmare...
1,26151671809,2009-12-31 19:06:01,WTF,5.858025e+06,63325829123,17742851,6,0,Just moved to Florida this year when my husban...
2,26151671837,2009-12-31 19:06:34,IAmA,6.217231e+06,26151623560,17736597,3,0,If I had a son and I saw him getting paid to f...
3,26151672754,2009-12-31 19:21:08,funny,6.182729e+06,26151672257,17745252,3,0,Yeah I guess it is larry miller. http://www.ad...
4,26151672788,2009-12-31 19:21:44,trees,6.090001e+06,63325830216,17743944,2,0,OxyClean
...,...,...,...,...,...,...,...,...,...
1903785,44473027435,2023-12-29 21:30:01,footballmanagergames,2.318601e+12,44471304599,2710827028,38,0,Fun fact. Loughgall has a population of 4 and ...
1903786,44475684754,2023-12-30 07:10:29,FIREUK,1.344849e+12,82049991346785,2711538273,14,0,Chat to your friend and potential new boss and...
1903787,44475940806,2023-12-30 08:08:23,ArgenGaming,NaN,82049990332297,2710523785,2,0,COMO QUE ESTABA 3USD YO PAGUE COMO 30 HACE 2 M...
1903788,44476579574,2023-12-30 10:02:17,teenagers,5.022138e+11,82049991413047,2711604535,1,0,Cornland
1903789,44485891446,2023-12-31 11:36:42,Abortiondebate,2.543632e+13,44484357231,2712468775,11,0,>I support easy access until 8 weeks. \n\n\nNo...

In [7]:
misses

0         26151671597
1         26151671665
2         26151672225
3         26151672735
4         26151672783
             ...
391205    44401254658
391206    44417927653
391207    44423010209
391208    44438405746
391209    44477335368
Name: id, Length: 391210, dtype: int64

In [8]:
# Sanity checks
validate.validate(df, misses)

✅ Found no duplicate comment IDs
✅ Found no duplicate misses
Everything good

## Basic analysis

In [12]:
kw_counts = {}
for kw in keywords:
    kw_counts[kw] = len(df[df[BODY].str.contains(re.compile(kw, flags=re.IGNORECASE))])
kw_counts

{'trauma': 947,
 'gaslight': 106,
 'trigger': 2844,
 'toxic': 1821,
 'manipulat': 1761,
 'microaggression': 7,
 'autis': 776,
 'adhd': 386,
 'ocd': 359,
 'ptsd': 383,
 'bipolar': 299,
 'anxiety': 1790,
 'depress': 4109,
 'psycho': 3337,
 'delusion': 987,
 'addict': 2711,
 'abus': 4703,
 'unstable': 434,
 'narcissis': 425,
 'neurodivergen': 0}

In [8]:
import polars as pl

pldf = pl.from_pandas(df)
pldf

shape: (1_903_790, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ id         ┆ time      ┆ sr_name   ┆ author_id ┆ … ┆ post_id   ┆ upvotes ┆ downvotes ┆ body      │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---       ┆ ---       │
│ i64        ┆ datetime[ ┆ str       ┆ f64       ┆   ┆ i64       ┆ i64     ┆ i64       ┆ str       │
│            ┆ ns]       ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 2615167154 ┆ 2009-12-3 ┆ IAmA      ┆ null      ┆ … ┆ 17741786  ┆ 2       ┆ 0         ┆ How often │
│ 9          ┆ 1         ┆           ┆           ┆   ┆           ┆         ┆           ┆ do you    │
│            ┆ 19:01:19  ┆           ┆           ┆   ┆           ┆         ┆           ┆ deal with │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ pat…      │
│ 2615167180 ┆ 2009-12-3 ┆ WTF       ┆ 5.858025e ┆ … ┆ 17742851  ┆ 6       ┆ 0         ┆ Just      │
│ 9          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆ moved to  │
│            ┆ 19:06:01  ┆           ┆           ┆   ┆           ┆         ┆           ┆ Florida   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ this yea… │
│ 2615167183 ┆ 2009-12-3 ┆ IAmA      ┆ 6.217231e ┆ … ┆ 17736597  ┆ 3       ┆ 0         ┆ If I had  │
│ 7          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆ a son and │
│            ┆ 19:06:34  ┆           ┆           ┆   ┆           ┆         ┆           ┆ I saw him │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ g…        │
│ 2615167275 ┆ 2009-12-3 ┆ funny     ┆ 6.182729e ┆ … ┆ 17745252  ┆ 3       ┆ 0         ┆ Yeah I    │
│ 4          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆ guess it  │
│            ┆ 19:21:08  ┆           ┆           ┆   ┆           ┆         ┆           ┆ is larry  │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ mille…    │
│ 2615167278 ┆ 2009-12-3 ┆ trees     ┆ 6.090001e ┆ … ┆ 17743944  ┆ 2       ┆ 0         ┆ OxyClean  │
│ 8          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆           │
│            ┆ 19:21:44  ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ 4447302743 ┆ 2023-12-2 ┆ footballm ┆ 2.3186e12 ┆ … ┆ 271082702 ┆ 38      ┆ 0         ┆ Fun fact. │
│ 5          ┆ 9         ┆ anagergam ┆           ┆   ┆ 8         ┆         ┆           ┆ Loughgall │
│            ┆ 21:30:01  ┆ es        ┆           ┆   ┆           ┆         ┆           ┆ has a     │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ popu…     │
│ 4447568475 ┆ 2023-12-3 ┆ FIREUK    ┆ 1.3448e12 ┆ … ┆ 271153827 ┆ 14      ┆ 0         ┆ Chat to   │
│ 4          ┆ 0         ┆           ┆           ┆   ┆ 3         ┆         ┆           ┆ your      │
│            ┆ 07:10:29  ┆           ┆           ┆   ┆           ┆         ┆           ┆ friend    │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ and       │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ potent…   │
│ 4447594080 ┆ 2023-12-3 ┆ ArgenGami ┆ null      ┆ … ┆ 271052378 ┆ 2       ┆ 0         ┆ COMO QUE  │
│ 6          ┆ 0         ┆ ng        ┆           ┆   ┆ 5         ┆         ┆           ┆ ESTABA    │
│            ┆ 08:08:23  ┆           ┆           ┆   ┆           ┆         ┆           ┆ 3USD YO   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ PAGUE …   │
│ 4447657957 ┆ 2023-12-3 ┆ teenagers ┆ 5.0221e11 ┆ … ┆ 271160453 ┆ 1       ┆ 0         ┆ Cornland  │
│ 4          ┆ 0         ┆           ┆           ┆   ┆ 5         ┆         ┆           ┆           │
│            ┆ 10:02:17  ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
│ 4448589144 ┆ 2023-12-3 ┆ Abortiond ┆ 2.5436e13 ┆ … ┆ 271246877 ┆ 11      ┆ 0         ┆ >I        │
│ 6          ┆ 1         ┆ ebate     ┆           ┆   ┆ 5         ┆         ┆           ┆ support   │
│            ┆ 11:36:42  ┆           ┆           ┆   ┆           ┆         ┆           ┆ easy      │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ access    │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ until 8…  │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [ ]:
kw_counts = {}
for kw in keywords:
    kw_counts[kw] = len(pldf.filter(pl.col(BODY).str.contains("(?i)" + kw)))

kw_counts

{'trauma': 947,
 'gaslight': 106,
 'trigger': 2844,
 'toxic': 1821,
 'manipulat': 1761,
 'microaggression': 7,
 'autis': 776,
 'adhd': 386,
 'ocd': 359,
 'ptsd': 383,
 'bipolar': 299,
 'anxiety': 1790,
 'depress': 4109,
 'psycho': 3337,
 'delusion': 987,
 'addict': 2711,
 'abus': 4703,
 'unstable': 434,
 'narcissis': 425,
 'neurodivergen': 0}

In [10]:
# Add a "Time range" column to a dataframe
import datetime

TIME_RANGE = "Time range"
"""Name of the column for storing time range"""

def with_time_range(df):
    dfs = []
    for time_range in config.time_ranges:
        start_time = datetime.datetime.combine(time_range.start_date, datetime.time(0, 0, 0))
        end_time = datetime.datetime.combine(time_range.end_date, datetime.time(0, 0, 0))
        filtered = df[(start_time <= df[TIME]) & (df[TIME] < end_time)].copy()
        filtered[TIME_RANGE] = time_range
        dfs.append(filtered)
    return pd.concat(dfs)

# Text cleaning

In [9]:
# Doing this stuff on all comments is slow, so let's just try it on a small sample

# sample_df = pldf.sample(5000)
# sample_df = pldf.filter(pl.col(BODY).str.contains_any(keywords))
sample_df = pldf.filter(pl.col(BODY).str.contains_any(["depress", "abus", "psycho", "addict"]))
sample_df

shape: (13_343, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬─────────┬───────────┬───────────┐
│ id         ┆ time      ┆ sr_name   ┆ author_id ┆ … ┆ post_id   ┆ upvotes ┆ downvotes ┆ body      │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---     ┆ ---       ┆ ---       │
│ i64        ┆ datetime[ ┆ str       ┆ f64       ┆   ┆ i64       ┆ i64     ┆ i64       ┆ str       │
│            ┆ ns]       ┆           ┆           ┆   ┆           ┆         ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═════════╪═══════════╪═══════════╡
│ 2615167283 ┆ 2009-12-3 ┆ politics  ┆ 5.433737e ┆ … ┆ 17746749  ┆ 5       ┆ 0         ┆ "Recovery │
│ 8          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆ "\n\nHow. │
│            ┆ 19:22:36  ┆           ┆           ┆   ┆           ┆         ┆           ┆ ..        │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ ironic.   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ L…        │
│ 2615169624 ┆ 2010-01-0 ┆ AskReddit ┆ 6.178793e ┆ … ┆ 17742734  ┆ 1       ┆ 0         ┆ Hey       │
│ 4          ┆ 1         ┆           ┆ 6         ┆   ┆           ┆         ┆           ┆ thanks    │
│            ┆ 04:32:09  ┆           ┆           ┆   ┆           ┆         ┆           ┆ this is   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ pretty    │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ swee…     │
│ 2615171482 ┆ 2010-01-0 ┆ reddit.co ┆ 6.386543e ┆ … ┆ 17756217  ┆ 1       ┆ 0         ┆ My toonst │
│ 3          ┆ 1         ┆ m         ┆ 6         ┆   ┆           ┆         ┆           ┆ orm.com   │
│            ┆ 14:03:15  ┆           ┆           ┆   ┆           ┆         ┆           ┆ review\n\ │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ nI a…     │
│ 2615172797 ┆ 2010-01-0 ┆ cogsci    ┆ 5.73455e6 ┆ … ┆ 17755779  ┆ 5       ┆ 0         ┆ I enjoyed │
│ 3          ┆ 1         ┆           ┆           ┆   ┆           ┆         ┆           ┆ the       │
│            ┆ 17:46:52  ┆           ┆           ┆   ┆           ┆         ┆           ┆ article   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ but they… │
│ 2615173009 ┆ 2010-01-0 ┆ books     ┆ null      ┆ … ┆ 17747865  ┆ 3       ┆ 0         ┆ >How can  │
│ 4          ┆ 1         ┆           ┆           ┆   ┆           ┆         ┆           ┆ novels    │
│            ┆ 18:22:52  ┆           ┆           ┆   ┆           ┆         ┆           ┆ not       │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ include   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ cl…       │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …       ┆ …         ┆ …         │
│ 4335990051 ┆ 2023-08-2 ┆ gameofthr ┆ 2.8381974 ┆ … ┆ 253423807 ┆ 33      ┆ 0         ┆ They      │
│ 3          ┆ 1         ┆ ones      ┆ e7        ┆   ┆ 1         ┆         ┆           ┆ walked    │
│            ┆ 00:53:33  ┆           ┆           ┆   ┆           ┆         ┆           ┆ out on    │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ the show, │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ t…        │
│ 4346650954 ┆ 2023-09-0 ┆ relations ┆ 5.2706e13 ┆ … ┆ 255362344 ┆ 3       ┆ 0         ┆ I used to │
│ 0          ┆ 2         ┆ hip_advic ┆           ┆   ┆ 2         ┆         ┆           ┆ be a weed │
│            ┆ 16:37:59  ┆ e         ┆           ┆   ┆           ┆         ┆           ┆ addict so │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ …         │
│ 4350244698 ┆ 2023-09-0 ┆ askphilos ┆ 3.9692568 ┆ … ┆ 255959347 ┆ 1       ┆ 0         ┆ Your post │
│ 2          ┆ 6         ┆ ophy      ┆ e7        ┆   ┆ 5         ┆         ┆           ┆ was       │
│            ┆ 19:02:46  ┆           ┆           ┆   ┆           ┆         ┆           ┆ removed   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ for viol… │
│ 4434803141 ┆ 2023-12-1 ┆ nope      ┆ 1.0909e12 ┆ … ┆ 269180706 ┆ -1      ┆ 0         ┆ Because   │
│ 0          ┆ 5         ┆           ┆           ┆   ┆ 9         ┆         ┆           ┆ the       │
│            ┆ 02:16:39  ┆           ┆           ┆   ┆           ┆         ┆           ┆ parents   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ weren't   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ th…       │
│ 4434988003 ┆ 2023-12-1 ┆ zoloft    ┆ 1.2928515 ┆ … ┆ 269191932 ┆ 1       ┆ 0         ┆ It cured  │
│ 1          ┆ 5         ┆           ┆ e7        ┆   ┆ 4         ┆         ┆           ┆ my        │
│            ┆ 09:12:52  ┆           ┆           ┆   ┆           ┆         ┆           ┆ anxiety   │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ and       │
│            ┆           ┆           ┆           ┆   ┆           ┆         ┆           ┆ depres…   │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴─────────┴───────────┴───────────┘

In [10]:
from bs4 import BeautifulSoup
import re
from umarkdown import markdown


def parse_markdown(body: str):
    html = markdown(body)
    soup = BeautifulSoup(html, features="html.parser")
    plaintext = soup.get_text(" ").strip()
    # Reddit uses ^ for superscript
    plaintext = plaintext.replace("^", " ")
    # Don't mess with links like 'reddit.com/r/foo', only remove r/foo and /r/foo alone
    plaintext = re.sub(r"((?<!com)/|(?<!/)\b)[rR]/\w+\b/?", "<SUBREDDIT>", plaintext)
    plaintext = re.sub(r"(/|\b)[uU]/\w+\b/?", "<USER>", plaintext)
    # Ge rid of escaped newlines
    plaintext = plaintext.replace(r"\n", " ")
    # Get rid of newlines and extra spaces
    plaintext = re.sub(r"\s+", " ", plaintext)
    return plaintext

In [11]:
sample_df = sample_df.with_columns(parsed=pl.col(BODY).map_elements(parse_markdown, return_dtype=pl.String))
sample_df

shape: (13_343, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ id         ┆ time      ┆ sr_name   ┆ author_id ┆ … ┆ upvotes ┆ downvotes ┆ body      ┆ parsed    │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆ datetime[ ┆ str       ┆ f64       ┆   ┆ i64     ┆ i64       ┆ str       ┆ str       │
│            ┆ ns]       ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 2615167283 ┆ 2009-12-3 ┆ politics  ┆ 5.433737e ┆ … ┆ 5       ┆ 0         ┆ "Recovery ┆ "Recovery │
│ 8          ┆ 1         ┆           ┆ 6         ┆   ┆         ┆           ┆ "\n\nHow. ┆ " How ... │
│            ┆ 19:22:36  ┆           ┆           ┆   ┆         ┆           ┆ ..        ┆ ironic.   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ ironic.   ┆ Lim…      │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ L…        ┆           │
│ 2615169624 ┆ 2010-01-0 ┆ AskReddit ┆ 6.178793e ┆ … ┆ 1       ┆ 0         ┆ Hey       ┆ Hey       │
│ 4          ┆ 1         ┆           ┆ 6         ┆   ┆         ┆           ┆ thanks    ┆ thanks    │
│            ┆ 04:32:09  ┆           ┆           ┆   ┆         ┆           ┆ this is   ┆ this is   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ pretty    ┆ pretty    │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ swee…     ┆ swee…     │
│ 2615171482 ┆ 2010-01-0 ┆ reddit.co ┆ 6.386543e ┆ … ┆ 1       ┆ 0         ┆ My toonst ┆ My toonst │
│ 3          ┆ 1         ┆ m         ┆ 6         ┆   ┆         ┆           ┆ orm.com   ┆ orm.com   │
│            ┆ 14:03:15  ┆           ┆           ┆   ┆         ┆           ┆ review\n\ ┆ review I  │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ nI a…     ┆ am a…     │
│ 2615172797 ┆ 2010-01-0 ┆ cogsci    ┆ 5.73455e6 ┆ … ┆ 5       ┆ 0         ┆ I enjoyed ┆ I enjoyed │
│ 3          ┆ 1         ┆           ┆           ┆   ┆         ┆           ┆ the       ┆ the       │
│            ┆ 17:46:52  ┆           ┆           ┆   ┆         ┆           ┆ article   ┆ article   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ but they… ┆ but they… │
│ 2615173009 ┆ 2010-01-0 ┆ books     ┆ null      ┆ … ┆ 3       ┆ 0         ┆ >How can  ┆ How can   │
│ 4          ┆ 1         ┆           ┆           ┆   ┆         ┆           ┆ novels    ┆ novels    │
│            ┆ 18:22:52  ┆           ┆           ┆   ┆         ┆           ┆ not       ┆ not       │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ include   ┆ include   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ cl…       ┆ cla…      │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ 4335990051 ┆ 2023-08-2 ┆ gameofthr ┆ 2.8381974 ┆ … ┆ 33      ┆ 0         ┆ They      ┆ They      │
│ 3          ┆ 1         ┆ ones      ┆ e7        ┆   ┆         ┆           ┆ walked    ┆ walked    │
│            ┆ 00:53:33  ┆           ┆           ┆   ┆         ┆           ┆ out on    ┆ out on    │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ the show, ┆ the show, │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ t…        ┆ t…        │
│ 4346650954 ┆ 2023-09-0 ┆ relations ┆ 5.2706e13 ┆ … ┆ 3       ┆ 0         ┆ I used to ┆ I used to │
│ 0          ┆ 2         ┆ hip_advic ┆           ┆   ┆         ┆           ┆ be a weed ┆ be a weed │
│            ┆ 16:37:59  ┆ e         ┆           ┆   ┆         ┆           ┆ addict so ┆ addict so │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ …         ┆ …         │
│ 4350244698 ┆ 2023-09-0 ┆ askphilos ┆ 3.9692568 ┆ … ┆ 1       ┆ 0         ┆ Your post ┆ Your post │
│ 2          ┆ 6         ┆ ophy      ┆ e7        ┆   ┆         ┆           ┆ was       ┆ was       │
│            ┆ 19:02:46  ┆           ┆           ┆   ┆         ┆           ┆ removed   ┆ removed   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ for viol… ┆ for viol… │
│ 4434803141 ┆ 2023-12-1 ┆ nope      ┆ 1.0909e12 ┆ … ┆ -1      ┆ 0         ┆ Because   ┆ Because   │
│ 0          ┆ 5         ┆           ┆           ┆   ┆         ┆           ┆ the       ┆ the       │
│            ┆ 02:16:39  ┆           ┆           ┆   ┆         ┆           ┆ parents   ┆ parents   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ weren't   ┆ weren't   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ th…       ┆ th…       │
│ 4434988003 ┆ 2023-12-1 ┆ zoloft    ┆ 1.2928515 ┆ … ┆ 1       ┆ 0         ┆ It cured  ┆ It cured  │
│ 1          ┆ 5         ┆           ┆ e7        ┆   ┆         ┆           ┆ my        ┆ my        │
│            ┆ 09:12:52  ┆           ┆           ┆   ┆         ┆           ┆ anxiety   ┆ anxiety   │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ and       ┆ and       │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆ depres…   ┆ depres…   │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

## Word2Vec

In [12]:
import gensim.downloader as api

model = api.load("glove-twitter-100")

In [24]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [13]:
from collections import defaultdict
import spacy

nlp = spacy.load("en_core_web_sm")

counts = defaultdict(lambda: 0)

for text in sample_df["parsed"]:
    # If there's dots touching words, separate them from those words
    text = re.sub(r"\.{2,}", " ... ", text)
    text = text.replace("-", " ")
    for tok in nlp(text):
        tok = tok.text.strip().lower()
        if re.fullmatch(r"\W*", tok):
            continue
        if re.fullmatch(r"\d+(\.\d*)?(/\d+)?", tok):
            tok = "<NUMBER>"
        if tok not in model.key_to_index:
            counts[tok] += 1

In [14]:
words = list(counts.keys())
counts_df = pl.DataFrame({"word": words, "count": [counts[word] for word in words]})
counts_df = counts_df.sort("count", descending=True)
counts_df

shape: (10_854, 2)
┌──────────────┬───────┐
│ word         ┆ count │
│ ---          ┆ ---   │
│ str          ┆ i64   │
╞══════════════╪═══════╡
│ <NUM>        ┆ 9812  │
│ and/or       ┆ 129   │
│ tl;dr        ┆ 97    │
│ downvote     ┆ 61    │
│ downvoted    ┆ 59    │
│ …            ┆ …     │
│ smg4s        ┆ 1     │
│ imwtlmoe     ┆ 1     │
│ splatfest    ┆ 1     │
│ pr1          ┆ 1     │
│ tangentially ┆ 1     │
└──────────────┴───────┘

In [15]:
counts_df.write_csv("bad.csv")

# Contextual embeddings

In [19]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

/usr/lib/python3.11/pty.py:89: RuntimeWarning: Using fork() can cause Polars to deadlock in the child process.
In addition, using fork() with Python in general is a recipe for mysterious
deadlocks and crashes.

The most likely reason you are seeing this error is because you are using the
multiprocessing module on Linux, which uses fork() by default. This will be
fixed in Python 3.14. Until then, you want to use the "spawn" context instead.

See https://docs.pola.rs/user-guide/misc/multiprocessing/ for details.

  pid, fd = os.forkpty()

Looking in indexes: https://download.pytorch.org/whl/cu118
Requirement already satisfied: torch in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (2.5.1+cu118)
Requirement already satisfied: torchvision in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (0.20.1+cu118)
Requirement already satisfied: torchaudio in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (2.5.1+cu118)
Requirement already satisfied: filelock in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (11.8.86)
Requirement already satisfied: triton==3.1.0 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from torchvision) (10.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)

In [48]:
import torch
from transformers import BertModel, BertTokenizer

# From https://medium.com/@r3d_robot/getting-contextualized-word-embeddings-with-bert-20798d8b43a4
model = BertModel.from_pretrained(
    "bert-base-uncased",
    output_hidden_states=True,
)
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")


def bert_text_preparation(text, tokenizer):
    """
    Preprocesses text input in a way that BERT can interpret.
    """
    marked_text = "[CLS] " + text + " [SEP]"
    tokenized_text = tokenizer.tokenize(marked_text)
    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1] * len(indexed_tokens)  # convert inputs to tensors
    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensor = torch.tensor([segments_ids])
    return tokenized_text, tokens_tensor, segments_tensor


def get_bert_embeddings(tokens_tensor, segments_tensor):
    """
    Obtains BERT embeddings for tokens.
    """
    # gradient calculation id disabled
    with torch.no_grad():
        # obtain hidden states
        outputs = model(tokens_tensor, segments_tensor)
        hidden_states = outputs[2]  # concatenate the tensors for all layers
    # use "stack" to create new dimension in tensor
    token_embeddings = torch.stack(hidden_states, dim=0)
    # remove dimension 1, the "batches"
    token_embeddings = torch.squeeze(token_embeddings, dim=1)
    # swap dimensions 0 and 1 so we can loop over tokens
    token_embeddings = token_embeddings.permute(1, 0, 2)
    # intialized list to store embeddings
    token_vecs_sum = []  # "token_embeddings" is a [Y x 12 x 768] tensor
    # where Y is the number of tokens in the sentence    # loop over tokens in sentence
    for token in token_embeddings:  # "token" is a [12 x 768] tensor
        # sum the vectors from the last four layers
        sum_vec = torch.sum(token[-4:], dim=0)
        token_vecs_sum.append(sum_vec)
    return token_vecs_sum

/home/ysthakur/.virtualenvs/datasci/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [49]:
sentences = [
    "bank",
    "he eventually sold the shares back to the bank at a premium.",
    "the bank strongly resisted cutting interest rates.",
    "the bank will supply and buy back foreign currency.",
    "the bank is pressing us for repayment of the loan.",
    "the bank left its lending rates unchanged.",
    "the river flowed over the bank.",
    "tall, luxuriant plants grew along the river bank.",
    "his soldiers were arrayed along the river bank.",
    "wild flowers adorned the river bank.",
    "two fox cubs romped playfully on the river bank.",
    "the jewels were kept in a bank vault.",
    "you can stow your jewellery away in the bank.",
    "most of the money was in storage in bank vaults.",
    "the diamonds are shut away in a bank vault somewhere.",
    "thieves broke into the bank vault.",
    "can I bank on your support?",
    "you can bank on him to hand you a reasonable bill for your services.",
    "don't bank on your friends to help you out of trouble.",
    "you can bank on me when you need money.",
    "i bank on your help.",
]

from collections import OrderedDict

context_embeddings = []
context_tokens = []
context_sentences = []

just_trauma = (
    pl_df.lazy()
    .filter(pl.col(BODY).str.contains("trauma"))
    .select(BODY)
    .collect()
    .to_series()
)

for sentence in just_trauma:
    tokenized_text, tokens_tensor, segments_tensors = bert_text_preparation(
        sentence, tokenizer
    )
    # todo handle long sentences
    if tokens_tensor.size(dim=1) > 512:
        continue
    list_token_embeddings = get_bert_embeddings(tokens_tensor, segments_tensors)
    # make ordered dictionary to keep track of the position of each   word
    tokens = OrderedDict()
    # loop over tokens in sensitive sentence
    for token in tokenized_text[1:-1]:
        # TODO account for subword tokenization
        if token != "trauma":
            continue
        # keep track of position of word and whether it occurs multiple times
        if token in tokens:
            tokens[token] += 1
        else:
            tokens[token] = 1  # compute the position of the current token
        token_indices = [i for i, t in enumerate(tokenized_text) if t == token]
        current_index = token_indices[
            tokens[token] - 1
        ]  # get the corresponding embedding
        token_vec = list_token_embeddings[current_index]

        # save values
        context_tokens.append(token)
        context_embeddings.append(token_vec)
        context_sentences.append(sentence)

In [50]:
# For visualizing at https://projector.tensorflow.org/

import csv

with open("metadata_output.tsv", "w+") as file_metadata, open(
    "embeddings_small.tsv", "w+"
) as tsvfile:
    writer = csv.writer(tsvfile, delimiter="\t")
    for token, embedding, sentence in zip(
        context_tokens, context_embeddings, context_sentences
    ):
        if token != "trauma":
            continue
        file_metadata.write(sentence + "\n")
        writer.writerow(embedding.numpy())

In [51]:
# Clustering
from sklearn.cluster import *

trauma_embeddings_with_inds = [
    (i, embedding)
    for i, embedding in enumerate(context_embeddings)
    if context_tokens[i] == "trauma"
]
trauma_embeddings = [embedding for i, embedding in trauma_embeddings_with_inds]

# clustering = DBSCAN(eps=0.01, min_samples=2).fit(trauma_embeddings)
# clustering = HDBSCAN(min_cluster_size=5).fit(trauma_embeddings)
# clustering = OPTICS().fit(trauma_embeddings)
# clustering = KMeans().fit(trauma_embeddings)
clustering = AffinityPropagation(verbose=True).fit(trauma_embeddings)
pd.Series(clustering.labels_).value_counts()

Converged after 27 iterations.

44    45
9     38
22    33
10    31
4     29
21    24
35    23
18    23
31    22
37    21
17    20
29    18
7     18
6     18
26    18
28    16
15    16
32    16
23    15
40    14
8     14
49    14
38    13
41    13
27    13
34    12
16    11
46    11
11    10
20    10
3     10
1     10
45    10
2      8
13     8
5      8
25     7
39     7
30     6
0      6
47     5
19     5
48     5
24     4
14     4
42     4
12     4
33     3
43     3
36     2
Name: count, dtype: int64

In [52]:
# For visualizing at https://projector.tensorflow.org/

import csv

with open("metadata_output.tsv", "w+") as file_metadata, open(
    "embeddings_small.tsv", "w+"
) as tsvfile:
    file_metadata.write("Sentence\tCluster\n")
    writer = csv.writer(tsvfile, delimiter="\t")
    for (i, embedding), cluster in zip(trauma_embeddings_with_inds, clustering.labels_):
        token = context_tokens[i]
        sentence = context_sentences[i]
        if token != "trauma":
            continue
        file_metadata.write(f"{sentence}\t{cluster}\n")
        writer.writerow(embedding.numpy())